### ISSUE TITLE
Mocking admin.messaging()

### ISSUE THREAD

**Issue by lukepighetti** [firebase/firebase-functions-test#25]
Is there a way to mock the various `firebase-admin` methods such as `firebase-admin.messaging()` ?

**Comment by laurenzlong** [comment]
There's nothing out of the box, but you can use Sinon [stubs](https://sinonjs.org/releases/v2.4.0/stubs/) or [spies](https://sinonjs.org/releases/v3.2.1/spies/) to mock any method.

**Comment by mayurdhurpate** [comment]
Hi, sorry for commenting on a closed issue, but I'm finding it difficult to mock the Firebase functions in Typescript. I'm using jest mocks and was recently trying to mock the `admin.messaging().sendToDevice` function.

```
const fcmMock = jest.spyOn(admin.messaging(),'sendToDevice');

fcmMock.mockImplementation(async (registrationToken: string | string[], payload: admin.messaging.MessagingPayload, options?: admin.messaging.MessagingOptions)=>{
      console.log('FCM Mock called with message: '+payload.notification+'\nToken ids:'+registrationToken);
      return new Promise<admin.messaging.MessagingDevicesResponse>(undefined);
}); 
```

Running this gets the following error because the return type object `MessagingDevicesResponse>(undefined)` requires some complex argument: 

> Argument of type 'undefined' is not assignable to parameter of type '(resolve: (value?: MessagingDevicesResponse | PromiseLike<MessagingDevicesResponse> | undefined) => void, reject: (reason?: any) => void) => void'.

**Is there something that can be done to provide easier mocking utilities for Firebase (which thankfully supports/[suggests](https://firebase.googleblog.com/2018/01/why-you-should-use-typescript-for.html) Typescript out of the [box](https://github.com/firebase/functions-samples/blob/master/typescript-getting-started/README.md)), especially since Firebase Functions requires a lot of mocking to be done during testing.**

For example, here is how I mocked `slackWebClient.chat.postMessage` :

```
slackMock.mockImplementation(async (message: string, conversationId: string)=>{
      console.log('Slacks Mock called with message: '+message+'\nConversation id:'+conversationId);
      return await chatUtils.slackWebClient.api.test()
    });  
```
Not so good example as `slackWebClient.api.test()` it still makes a server call and has a different intended purpose, but helps in writing a mock in Typescript without worrying about the underlying implementation. 

Please guide if there is something I'm missing. I've recently started to work on Firebase testing.
